export { Button } from "./ui/button"; 
export { Input } from "./ui/input"; 

export { BillingCard as Card } from "./billing/card"
export { CreditCard } from "./billing/credit-card"
export { Information } from "./billing/information"
export { Invoices } from "./billing/invoices"
export { Method } from "./billing/method"
export { Transactions } from "./billing/transactions"

export { Card as CardPage } from "./dashboard/card"
export { Tables } from "./dashboard/Tables/tables"

export { Conversations } from "./profile/conversations"
export { Profile } from "./profile/profile"
export { PlatformSettings } from "./profile/platform-settings"
export { ProfileInformation } from "./profile/profile-information"
export { Projects } from "./profile/projects"

export { BuildSvg } from "./icons/build"
export { SvgEdit } from "./icons/edit"
export { OverviewSvg } from "./icons/overview"
export { SvgTrash } from "./icons/trash"
export { MultiDocumentSvg } from "./icons/multidocument"
export { SvgPerson } from "./icons/person"
export { UserSvg } from "./icons/user"
export { KeySvg } from "./icons/key"
export { SvgWallet } from "./icons/wallet"
export { VertSvg } from "./icons/vert"
export { UpperSvg } from "./icons/upper"
export { TwitterSvg } from "./icons/twitter"
export { TextDocumentSvg } from "./icons/textdocument"
export { SvgTable } from "./icons/table"
export { SvgSettings } from "./icons/settings"
export { SvgSearch } from "./icons/search"
export { SvgRocket } from "./icons/rocket"
export { SvgPaypal } from "./icons/paypal"
export { PendingSvg } from "./icons/pending"
export { SvgNotifications } from "./icons/notifications"
export { InstagramSvg } from "./icons/instagram"
export { SvgHome } from "./icons/home"
export { FacebookSvg } from "./icons/facebook"
export { SvgDocument } from "./icons/document"
export { CheckBoxSvg } from "./icons/checkbox"
export { AppleSvg } from "./icons/apple"
export { LowerSvg } from "./icons/lower"
export { SvgBilling } from "./icons/billing"
export { CalendarSvg } from "./icons/calendar"

export { AuthorTable } from "./table/author-table"
export { ProjectsTable } from "./table/projects-table"

export { SignInBg } from "./register/sign-bg"
export { SignNav } from "./register/sign-nav"

export { Bg } from "./bg"
export { NavBar } from "./ui/navbar"
export { Sidebar } from "./ui/sidebar"

export { SaleTable } from "./dashboard/Tables/sale-table"
export { TraficTable } from "./dashboard/Tables/trafic-table"
export { VisitTable } from "./dashboard/Tables/visit-table"
export { PerformanceTable } from "./dashboard/Tables/performance-table"

export { BillingPage } from "../pages/billing"
export { TablePage } from "../pages/tables"
export { Dashboard } from "../pages/dashboard"
export { ProfilePage } from "../pages/profile"
export { LoginLayout } from "../layout/loginlayout"
export { SignIn } from "../pages/signin"
export { Register } from "../pages/register"


// export { visitDataProps, traficDataProps, cardDatasProps, authorsDataProps, projectsDataProps,paymentInfoProps, paymentMethodProps, billingInformationProps, paymentInvoicesProps, userDataProps, salesOverviewProps, performanceProps } from "./type"